import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.13.0/firebase-app.js';
import { getFirestore, addDoc, collection, serverTimestamp, getDocs, query, where, orderBy, limit } from 'https://www.gstatic.com/firebasejs/12.13.0/firebase-firestore.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.13.0/firebase-auth.js';
const firebaseConfig={apiKey:'AIzaSyDeqA-ek9IULGzqWSP3lcNhRVdRprKHJYg',authDomain:'quickmaths-84461.firebaseapp.com',projectId:'quickmaths-84461',storageBucket:'quickmaths-84461.firebasestorage.app',messagingSenderId:'620869920659',appId:'1:620869920659:web:805509d873006044856a66',measurementId:'G-NN37WM99MK'};
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app),provider=new GoogleAuthProvider();
const q=s=>document.querySelector(s);const els={menuButton:q('#menuButton'),menuPanel:q('#menuPanel'),pages:{practice:q('#practicePage'),stats:q('#statsPage'),tips:q('#tipsPage'),history:q('#historyPage')},versionSelect:q('#versionSelect'),topicSelect:q('#topicSelect'),topicCaption:q('#topicCaption'),tipsContainer:q('#tipsContainer'),periodFilter:q('#periodFilter'),questionText:q('#questionText'),answerInput:q('#answerInput'),submitButton:q('#submitButton'),feedback:q('#feedback'),authButton:q('#authButton'),logoutButton:q('#logoutButton'),totalQuestions:q('#totalQuestions'),correctCount:q('#correctCount'),wrongCount:q('#wrongCount'),avgTime:q('#avgTime'),accuracyRate:q('#accuracyRate'),activityCalendar:q('#activityCalendar'),recentAttempts:q('#recentAttempts'),difficultyChart:q('#difficultyChart'),trendChart:q('#trendChart'),openHistoryModal:q('#openHistoryModal'),closeHistoryModal:q('#closeHistoryModal'),historyModal:q('#historyModal'),historyContent:q('#historyContent')};
let versions=[],topic='square-roots',current,userId='anonymous',start=0;const attemptsKey='attempts',cardsKey='sr_cards';
const tips={
'square-roots':['Learn anchor squares 1²..40².','Bracket number between perfect squares.','Estimate ratio within interval.','Use last-digit clues for perfect squares.'],
'percentages':['10%=divide by 10, 1%=divide by 100.','Use 5%=half of 10%, 15%=10%+5%.','Find x% of y by y*x/100.','For increase/decrease use base ± percent of base.']};
const pool=(l)=>topic==='square-roots'?(l===1?[1,20]:l===2?[10,60]:l===3?[40,140]:[80,250]):(l===1?[10,99]:l===2?[100,499]:l===3?[500,1999]:[2000,9999]);
const attempts=()=>JSON.parse(localStorage.getItem(attemptsKey)||'[]'); const cards=()=>JSON.parse(localStorage.getItem(cardsKey)||'{}'); const saveCards=v=>localStorage.setItem(cardsKey,JSON.stringify(v));
const level=()=>{const r=attempts().slice(-30).filter(a=>a.topic===topic);const acc=r.length?r.filter(a=>a.isCorrect).length/r.length:1;return acc>0.9&&r.length>14?4:acc>0.78?3:acc>0.6?2:1};
function makeQ(){const l=level(),[min,max]=pool(l),c=cards(),now=Date.now();const due=Object.entries(c).filter(([,v])=>v.nextReview<=now&&v.topic===topic).sort((a,b)=>(b[1].priority||1)-(a[1].priority||1)); if(topic==='square-roots'){const root=due.length?+due[0][0]:Math.floor(Math.random()*(max-min+1))+min; return {id:String(root),answer:root,prompt:`√${root*root}`,level:l};}
const base=Math.floor(Math.random()*(max-min+1))+min,pct=[5,10,12,15,20,25,30,40,50,75][Math.floor(Math.random()*10)],ans=Number((base*pct/100).toFixed(2));return{id:`${pct}%of${base}`,answer:ans,prompt:`${pct}% of ${base}`,level:l};}
function nextQ(){current=makeQ();els.questionText.textContent=`${current.prompt} (L${current.level})`;els.answerInput.value='';els.feedback.textContent='';els.feedback.className='feedback';start=performance.now();els.answerInput.focus();}
function saveLocal(r){const a=attempts();a.push(r);localStorage.setItem(attemptsKey,JSON.stringify(a));const c=cards();c[current.id]=c[current.id]||{efactor:2.5,interval:1,repetition:0,nextReview:0,priority:1,topic};const card=c[current.id];const g=r.isCorrect?(r.timeTakenMs<1300?5:r.timeTakenMs<2200?4:3):2;if(g<3){card.repetition=0;card.interval=1;card.priority*=1.7;} else {card.repetition+=1;card.interval=card.repetition===1?1:card.repetition===2?6:Math.round(card.interval*card.efactor);card.priority=Math.max(1,card.priority*0.92);} card.efactor=Math.max(1.3,card.efactor+(0.1-(5-g)*(0.08+(5-g)*0.02)));card.nextReview=Date.now()+card.interval*86400000;card.topic=topic;saveCards(c);}
async function saveFS(r){try{await addDoc(collection(db,'attempts'),{...r,userId,topic,createdAt:serverTimestamp()});return true;}catch{return false;}}
async function submit(){const given=Number(els.answerInput.value);if(!Number.isFinite(given))return;const rec={question:current.prompt,answerGiven:given,answerCorrect:current.answer,isCorrect:Math.abs(given-current.answer)<0.01,timeTakenMs:Math.round(performance.now()-start),level:current.level,topic,createdAt:new Date().toISOString()};saveLocal(rec);const ok=await saveFS(rec);els.feedback.textContent=rec.isCorrect?`Correct ${ok?'• local+cloud':'• local only'}`:`Incorrect. Answer: ${current.answer}`;els.feedback.className=`feedback ${rec.isCorrect?'ok':'bad'}`;draw();setTimeout(nextQ,850);}
async function syncFS(){try{const qr=query(collection(db,'attempts'),where('userId','==',userId),orderBy('createdAt','desc'),limit(500));const s=await getDocs(qr);const remote=[];s.forEach(d=>remote.push(d.data()));if(remote.length)localStorage.setItem(attemptsKey,JSON.stringify(remote.reverse()));draw();}catch{}}
function filtered(){const p=els.periodFilter.value,a=attempts().filter(x=>x.topic===topic);if(p==='all')return a;const cut=Date.now()-Number(p)*86400000;return a.filter(x=>new Date(x.createdAt).getTime()>=cut);}
function draw(){const list=filtered(),t=list.length,c=list.filter(a=>a.isCorrect).length,w=t-c,avg=t?Math.round(list.reduce((s,a)=>s+a.timeTakenMs,0)/t):0;els.totalQuestions.textContent=t;els.correctCount.textContent=c;els.wrongCount.textContent=w;els.avgTime.textContent=avg;els.accuracyRate.textContent=`${t?Math.round(c*100/t):0}%`;els.activityCalendar.innerHTML='';const map={};list.forEach(a=>{const d=new Date(a.createdAt).toISOString().slice(0,10);map[d]=(map[d]||0)+1;});for(let i=30;i>=0;i--){const d=new Date(Date.now()-i*86400000).toISOString().slice(0,10),n=map[d]||0,e=document.createElement('div');e.className=`day-cell ${n>20?'level-4':n>10?'level-3':n>4?'level-2':n>0?'level-1':''}`;els.activityCalendar.append(e);}els.recentAttempts.innerHTML='';const g={};list.slice().reverse().forEach(a=>{const d=new Date(a.createdAt).toLocaleDateString();(g[d]=g[d]||[]).push(a)});Object.entries(g).slice(0,8).forEach(([d,arr])=>{const b=document.createElement('div');b.className='attempt-group';b.innerHTML=`<h4>${d} • ${arr.length} attempts</h4>`;arr.slice(0,20).forEach(a=>{const r=document.createElement('div');r.className='attempt-row';r.innerHTML=`<span>${a.question}</span><span>${a.isCorrect?'✓':'✗'}</span><span>${a.timeTakenMs}ms</span><span>L${a.level||1}</span>`;b.append(r);});els.recentAttempts.append(b);});}
function showTips(){els.tipsContainer.innerHTML=tips[topic].map((t,i)=>`<article><h3>Step ${i+1}</h3><p>${t}</p></article>`).join('');els.topicCaption.textContent=topic==='square-roots'?'Square roots with progression + spaced repetition':'Percentages with progression + spaced repetition';}
async function loadVersions(){const meta=await fetch('version.json').then(r=>r.json()).catch(()=>null);versions=meta?.availableVersions?.map(v=>v.version)||['5.0.0'];els.versionSelect.innerHTML='';versions.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v+(v===meta.currentVersion?' current':'');if(v===meta.currentVersion)o.selected=true;els.versionSelect.append(o);});}
async function openHistory(){const t=await fetch('VERSION_HISTORY.md').then(r=>r.text()).catch(()=> 'Unable');const blocks=t.split('\n## ').filter(Boolean);els.historyContent.innerHTML=blocks.map((b,i)=>{const x=(i?`## ${b}`:b).split('\n').filter(Boolean);return `<article class='history-card'><h4>${x[0]}</h4><ul>${x.slice(1).map(i=>`<li>${i.replace(/^-\s*/,'')}</li>`).join('')}</ul></article>`}).join('');if(!els.historyModal.open)els.historyModal.showModal();}
function showPage(p){Object.entries(els.pages).forEach(([k,v])=>v.classList.toggle('active',k===p));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='stats')draw();if(p==='history')openHistory();}
els.submitButton.addEventListener('click',submit);els.answerInput.addEventListener('keydown',e=>e.key==='Enter'&&submit());els.periodFilter.addEventListener('change',draw);els.topicSelect.addEventListener('change',e=>{topic=e.target.value;showTips();draw();nextQ();});
els.versionSelect.addEventListener('change',e=>{const v=e.target.value;if(v==='5.0.0'){location.href='index.html';return;}location.href=`archives/${v}/index.html`;});
els.menuButton.addEventListener('click',()=>els.menuPanel.classList.toggle('hidden'));document.querySelectorAll('#menuPanel [data-page], .bottom-tabs [data-page]').forEach(b=>b.addEventListener('click',()=>{showPage(b.dataset.page);els.menuPanel.classList.add('hidden');}));
els.authButton.addEventListener('click',()=>signInWithPopup(auth,provider));els.logoutButton.addEventListener('click',()=>signOut(auth));onAuthStateChanged(auth,u=>{userId=u?.uid||'anonymous';els.authButton.textContent=u?`Logged in: ${u.displayName}`:'Login / Signup with Google';els.logoutButton.classList.toggle('hidden',!u);if(u)syncFS();});
els.openHistoryModal.addEventListener('click',openHistory);els.closeHistoryModal.addEventListener('click',()=>els.historyModal.close());
await loadVersions();showTips();showPage('practice');draw();nextQ();
