import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.13.0/firebase-app.js';
import { getFirestore, addDoc, collection, serverTimestamp, getDocs, query, where, orderBy, limit } from 'https://www.gstatic.com/firebasejs/12.13.0/firebase-firestore.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.13.0/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyDeqA-ek9IULGzqWSP3lcNhRVdRprKHJYg',authDomain:'quickmaths-84461.firebaseapp.com',projectId:'quickmaths-84461',storageBucket:'quickmaths-84461.firebasestorage.app',messagingSenderId:'620869920659',appId:'1:620869920659:web:805509d873006044856a66',measurementId:'G-NN37WM99MK'};
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app),provider=new GoogleAuthProvider();
const q=s=>document.querySelector(s);
const els={menuButton:q('#menuButton'),menuPanel:q('#menuPanel'),pages:{practice:q('#practicePage'),stats:q('#statsPage'),tips:q('#tipsPage'),history:q('#historyPage')},versionSelect:q('#versionSelect'),questionText:q('#questionText'),answerInput:q('#answerInput'),submitButton:q('#submitButton'),feedback:q('#feedback'),authButton:q('#authButton'),logoutButton:q('#logoutButton'),totalQuestions:q('#totalQuestions'),correctCount:q('#correctCount'),wrongCount:q('#wrongCount'),avgTime:q('#avgTime'),accuracyRate:q('#accuracyRate'),activityCalendar:q('#activityCalendar'),recentAttempts:q('#recentAttempts'),openHistoryModal:q('#openHistoryModal'),closeHistoryModal:q('#closeHistoryModal'),historyModal:q('#historyModal'),historyContent:q('#historyContent')};
let versionMeta=null,userId='anonymous',current,start=0;
const attemptsKey='attempts';
const attempts=()=>JSON.parse(localStorage.getItem(attemptsKey)||'[]');
function makeQ(){ const r=Math.floor(Math.random()*60)+1; return {prompt:`√${r*r}`,answer:r}; }
function nextQ(){ current=makeQ(); els.questionText.textContent=current.prompt; els.answerInput.value=''; els.feedback.textContent=''; start=performance.now(); }
function draw(){ const list=attempts(); const t=list.length,c=list.filter(a=>a.isCorrect).length,w=t-c,avg=t?Math.round(list.reduce((s,a)=>s+a.timeTakenMs,0)/t):0; els.totalQuestions.textContent=t; els.correctCount.textContent=c; els.wrongCount.textContent=w; els.avgTime.textContent=avg; els.accuracyRate.textContent=`${t?Math.round(c*100/t):0}%`; }
async function saveFS(r){ try{ await addDoc(collection(db,'attempts'),{...r,userId,topic:'square-roots',createdAt:serverTimestamp()}); }catch{} }
async function submit(){ const given=Number(els.answerInput.value); if(!Number.isFinite(given)) return; const rec={question:current.prompt,answerGiven:given,answerCorrect:current.answer,isCorrect:Math.abs(given-current.answer)<0.01,timeTakenMs:Math.round(performance.now()-start),createdAt:new Date().toISOString()}; const list=attempts(); list.push(rec); localStorage.setItem(attemptsKey,JSON.stringify(list)); await saveFS(rec); els.feedback.textContent=rec.isCorrect?'Correct':`Incorrect. Answer: ${current.answer}`; draw(); setTimeout(nextQ,850); }
async function fetchWithFallback(paths, parser='json'){ for(const p of paths){ try{ const r=await fetch(p); if(!r.ok) continue; return parser==='json'?await r.json():await r.text(); }catch{} } return null; }
function viewedVersion(){ const m=window.location.pathname.match(/\/archives\/([^/]+)\//); return m?m[1]:versionMeta?.currentVersion; }
async function loadVersions(){ const meta=await fetchWithFallback(['../../version.json','version.json'],'json'); versionMeta=meta||{currentVersion:'7.3.2',availableVersions:[{version:'7.3.2',archivePath:'archives/7.3.2'}]}; els.versionSelect.innerHTML=''; versionMeta.availableVersions.forEach(v=>{ const o=document.createElement('option'); o.value=v.version; o.textContent=v.version; if(v.version===viewedVersion()) o.selected=true; els.versionSelect.append(o); }); }
async function openHistory(){ const t=await fetchWithFallback(['../../VERSION_HISTORY.md','VERSION_HISTORY.md'],'text'); els.historyContent.textContent=t||'Unable to load version history'; if(!els.historyModal.open) els.historyModal.showModal(); }
els.versionSelect.addEventListener('change',e=>{ const v=e.target.value; const base=window.location.pathname.includes('/archives/')?window.location.pathname.split('/archives/')[0]:window.location.pathname.replace(/\/[^/]*$/,''); const root=`${window.location.origin}${base}`; const target=versionMeta.availableVersions.find(x=>x.version===v); if(!target) return; window.location.href=v===versionMeta.currentVersion?`${root}/index.html`:`${root}/${target.archivePath}/index.html`; });
els.submitButton.addEventListener('click',submit); els.answerInput.addEventListener('keydown',e=>e.key==='Enter'&&submit());
els.menuButton.addEventListener('click',()=>els.menuPanel.classList.toggle('hidden')); document.querySelectorAll('#menuPanel [data-page], .bottom-tabs [data-page]').forEach(b=>b.addEventListener('click',()=>{Object.entries(els.pages).forEach(([k,v])=>v.classList.toggle('active',k===b.dataset.page)); if(b.dataset.page==='stats') draw(); if(b.dataset.page==='history') openHistory();}));
els.authButton.addEventListener('click',()=>signInWithPopup(auth,provider)); els.logoutButton.addEventListener('click',()=>signOut(auth)); onAuthStateChanged(auth,u=>{userId=u?.uid||'anonymous'; els.authButton.textContent=u?`Logged in: ${u.displayName}`:'Login / Signup with Google'; els.logoutButton.classList.toggle('hidden',!u);});
els.openHistoryModal.addEventListener('click',openHistory); els.closeHistoryModal.addEventListener('click',()=>els.historyModal.close());
await loadVersions(); draw(); nextQ();
